import { differenceInCalendarDays } from 'date-fns';
import { prisma } from './prisma';
import { fetchAndParseICal } from './icalParser';

export const VALID_CHANNELS = ['airbnb', 'gathern', 'booking.com'] as const;
export type Channel = typeof VALID_CHANNELS[number];

export interface SyncResult {
  integrationId: string;
  tenantId: string;
  channelName: string;
  roomId: string;
  imported: number;
  updated: number;
  canceled: number;
  skipped: number;
  blocksRemoved: number; // Previously-imported "[…block]" rows deleted because syncBlocks was OFF
  errors: string[];
  success: boolean;
  message: string;
}

export function parseGuestName(summary: string, description: string | null | undefined, channel: string): string {
  const s = (summary || '').trim();

  // Explicit host blocks (not guest reservations)
  if (!s || /closed|not available|unavailable/i.test(s)) {
    return `[${channel} block]`;
  }

  // Airbnb privacy mode: SUMMARY is literally "Reserved" — guest name never leaves Airbnb.
  // The reservation code lives in the DESCRIPTION's "Reservation URL"; surface that so the
  // host can cross-reference the Airbnb inbox.
  if (/^reserved$/i.test(s)) {
    // Airbnb URL pattern is the strongest signal \u2014 works regardless of declared channel
    const airbnbCode = description?.match(/airbnb\.com\/hosting\/reservations\/details\/([A-Z0-9]+)/i)?.[1];
    if (airbnbCode) return `Airbnb \u2022 ${airbnbCode}`;
    // Gathern: description contains "Booking ID: 11180423 Guest:"
    const gathernId = description?.match(/Booking\s*ID\s*:\s*(\d+)/i)?.[1];
    if (gathernId) return `Gathern \u2022 ${gathernId}`;
    // Channel-aware fallback (no longer hardcodes "Airbnb" for non-Airbnb feeds)
    return `[${channel} guest]`;
  }

  // Legacy / fuller-disclosure patterns seen on some listings
  const byMatch = s.match(/(?:reservation|booking)\s+(?:by|from)\s+(.+)/i);
  if (byMatch) return byMatch[1].trim();

  // Generic placeholders: "Booking", "Reservation" with nothing after
  if (/^(booking|reservation)\s*$/i.test(s)) return `[${channel} guest]`;

  // Fallback: raw SUMMARY (handles Gathern which often includes real Arabic names)
  return s || 'Guest';
}

// True when the existing guestName looks like something we (or a platform placeholder)
// generated automatically — safe to overwrite on re-sync. User-typed names are preserved.
function looksAutoGenerated(name: string | null | undefined): boolean {
  if (!name) return true;
  const n = name.trim();
  if (!n) return true;
  if (/^\[.+\]$/.test(n)) return true;              // e.g. "[airbnb guest]", "[airbnb block]"
  if (/^reserved$/i.test(n)) return true;           // legacy default from older sync
  if (/^gathern\s*•\s*\d+$/i.test(n)) return true; // "Gathern • 11180423"
  if (/^airbnb\s*\u2022\s*[A-Z0-9]+$/i.test(n)) return true; // "Airbnb • HMXXXX"
  if (n === 'Guest') return true;
  return false;
}

/**
 * True when stored notes look like the raw iCal description we used to dump in
 * (Airbnb/Gathern/Booking.com all surface "Reservation URL:" + "Phone Number...").
 * Such notes are safe to overwrite/clear on re-sync. User-typed notes are preserved.
 */
function looksAutoNotes(notes: string | null | undefined): boolean {
  if (!notes) return true;
  const n = notes.trim();
  if (!n) return true;
  if (/Reservation URL:/i.test(n)) return true;
  if (/Phone Number\s*\(Last\s*\d+\s*Digits?\)/i.test(n)) return true;
  if (/^https?:\/\/\S+\s*$/i.test(n)) return true;
  // Gathern reservation description: "Booking ID: 11180423 Guest:" (with name often empty)
  if (/^Booking\s*ID\s*:\s*\d+/i.test(n)) return true;
  // Gathern host-block placeholder
  if (/^Host\s+blocked\s*$/i.test(n)) return true;
  return false;
}

/** True when guestPhone is empty or a sync-generated "•••• 1234" stub. */
function looksAutoPhone(phone: string | null | undefined): boolean {
  if (!phone) return true;
  const p = phone.trim();
  if (!p) return true;
  if (/^[•·]+\s*\d{2,6}$/.test(p)) return true;
  return false;
}

/**
 * Pull structured fields out of an iCal DESCRIPTION so they can live in their own
 * Booking columns (externalUrl, externalReservationId, guestPhone) instead of being
 * encoded into guestName or polluting the notes field.
 */
export function extractFromDescription(description: string | null | undefined): {
  externalUrl: string | null;
  externalReservationId: string | null;
  phoneStub: string | null;
} {
  if (!description) return { externalUrl: null, externalReservationId: null, phoneStub: null };
  const text = description.replace(/\\n/g, '\n');

  // ── Reservation URL ──
  let externalUrl: string | null = null;
  const labeled = text.match(/Reservation URL:\s*(https?:\/\/\S+)/i);
  if (labeled) {
    externalUrl = labeled[1];
  } else {
    const any = text.match(/https?:\/\/\S+/i);
    if (any) externalUrl = any[0];
  }
  if (externalUrl) externalUrl = externalUrl.replace(/[).,;]+$/, '');

  // ── Reservation code (Airbnb HM-prefixed code, or Gathern numeric Booking ID) ──
  let externalReservationId: string | null = null;
  const airbnbCode = text.match(/airbnb\.com\/hosting\/reservations\/details\/([A-Z0-9]+)/i);
  if (airbnbCode) {
    externalReservationId = airbnbCode[1].toUpperCase();
  } else {
    const gathernId = text.match(/Booking\s*ID\s*:\s*(\d+)/i);
    if (gathernId) externalReservationId = gathernId[1];
  }

  // ── Phone last 4 digits ──
  let phoneStub: string | null = null;
  const last = text.match(/Phone Number\s*\(Last\s*(\d+)\s*Digits?\)\s*:\s*(\d+)/i);
  if (last) {
    phoneStub = `•••• ${last[2]}`;
  }

  return { externalUrl, externalReservationId, phoneStub };
}

export type SyncMode = 'all' | 'future';

export async function performSync(integration: any, tenantId: string, mode?: SyncMode): Promise<SyncResult> {
  let imported = 0, updated = 0, canceled = 0, skipped = 0;
  const errors: string[] = [];

  let events;
  try {
    events = await fetchAndParseICal(integration.icalUrl);
  } catch (err: any) {
    const message = `Failed to fetch iCal: ${err.message}`;
    await prisma.channelIntegration.update({
      where: { id: integration.id },
      data: { lastSyncedAt: new Date(), lastSyncStatus: 'error', lastSyncMessage: message },
    });
    return { integrationId: integration.id, tenantId, channelName: integration.channelName, roomId: integration.roomId, imported: 0, updated: 0, canceled: 0, skipped: 0, blocksRemoved: 0, errors: [message], success: false, message };
  }

  // Lookback resolution. Explicit `mode` arg wins (legacy callers + override on the row);
  // otherwise the per-integration `syncLookbackDays` field decides.
  //   -1 / 'all'     → no cutoff, keep every event in the feed
  //   0 / 'future'   → events ending today onwards only (original behaviour)
  //   N >= 1         → events ending within the last N days
  //   null/undefined → fall back to 'future' so existing rows behave as before
  const lookbackDays: number = (() => {
    if (mode === 'all') return -1;
    if (mode === 'future') return 0;
    const stored = (integration as any).syncLookbackDays;
    if (stored === null || stored === undefined) return 0;
    return stored;
  })();
  if (lookbackDays !== -1) {
    const cutoff = new Date();
    cutoff.setHours(0, 0, 0, 0);
    if (lookbackDays > 0) cutoff.setDate(cutoff.getDate() - lookbackDays);
    const before = events.length;
    events = events.filter((e) => e.end >= cutoff);
    skipped += before - events.length;
  }

  // Block filter: by default, skip "Closed / Not available / Unavailable" events
  // (Gathern + Airbnb send a separate event per blocked day → calendar gets flooded).
  // The user can opt-in per integration via integration.syncBlocks.
  const syncBlocks = !!integration.syncBlocks;
  const isBlockEvent = (e: { summary: string }) => {
    const s = (e.summary || '').trim();
    return !s || /closed|not available|unavailable/i.test(s);
  };
  let blocksRemoved = 0;
  if (!syncBlocks) {
    // 1) Drop incoming block events from this sync run
    const before = events.length;
    events = events.filter((e) => !isBlockEvent(e));
    skipped += before - events.length;

    // 2) Sweep — delete previously-imported blocks for this integration so
    //    turning off syncBlocks immediately cleans the calendar. We match by
    //    the auto-generated guestName placeholder (`[<channel> block]`) plus
    //    externalChannel + room scope, so user-typed bookings are never touched.
    const sweep = await prisma.booking.deleteMany({
      where: {
        tenantId,
        room: integration.roomId,
        externalChannel: integration.channelName,
        guestName: { startsWith: '[', endsWith: 'block]' },
      },
    });
    blocksRemoved = sweep.count;
  }

  // ── Batch lookup (C1) ──
  // One findMany instead of N findFirst calls — was the largest performance hot
  // spot. With a 100-event feed this drops 100 sequential round trips to one.
  const existingBookings = events.length > 0
    ? await prisma.booking.findMany({
        where: { tenantId, externalId: { in: events.map((e) => e.uid) } },
      })
    : [];
  const existingByUid = new Map<string, (typeof existingBookings)[number]>();
  for (const b of existingBookings) {
    if (b.externalId) existingByUid.set(b.externalId, b);
  }

  // ── UID-drift fingerprint index ──
  // Airbnb/Gathern occasionally change the iCal UID for an unchanged reservation
  // (re-export, host reconnect, query-param shifts). Without this rescue, the
  // event misses the UID lookup → CREATE runs → fresh row with nightPrice=0 →
  // the user's manually-entered price appears wiped, and their original row
  // gets orphan-canceled below. We fingerprint already-synced bookings on this
  // (room + channel) by their check-in/out dates so we can re-link them to the
  // new UID and preserve all price fields.
  const driftCandidates = await prisma.booking.findMany({
    where: {
      tenantId,
      room: integration.roomId,
      externalChannel: integration.channelName,
      externalId: { not: null },
    },
    select: {
      id: true,
      externalId: true,
      checkIn: true,
      checkOut: true,
      status: true,
    },
  });
  const fingerprint = (start: Date, end: Date) =>
    `${start.toISOString().slice(0, 10)}|${end.toISOString().slice(0, 10)}`;
  const driftByDates = new Map<string, typeof driftCandidates[number]>();
  for (const b of driftCandidates) {
    const key = fingerprint(b.checkIn, b.checkOut);
    // Prefer non-canceled candidates; only use a canceled one if nothing better matched.
    const prior = driftByDates.get(key);
    if (!prior || (prior.status === 'canceled' && b.status !== 'canceled')) {
      driftByDates.set(key, b);
    }
  }

  // ── Pre-claim booking-number range (C2) ──
  // We used to update Tenant.nextBookingNumber once per NEW booking. Now we claim
  // the entire range in a single atomic increment (+N), then assign sequentially.
  // If a create fails mid-loop, we may leave a gap in the user's invoice numbers —
  // acceptable trade-off for the perf win. Booking numbers are not contractual.
  const newCount = events.filter((e) => e.uid && !existingByUid.has(e.uid)).length;
  let nextBookingNumberCursor = 0;
  if (newCount > 0) {
    const claimed = await prisma.tenant.update({
      where: { id: tenantId },
      data: { nextBookingNumber: { increment: newCount } },
      select: { nextBookingNumber: true },
    });
    nextBookingNumberCursor = claimed.nextBookingNumber - newCount;
  }

  for (const event of events) {
    try {
      const nights = differenceInCalendarDays(event.end, event.start);
      if (nights <= 0) { skipped++; continue; }

      const now = new Date();
      let status: string;
      if (event.status === 'CANCELLED') {
        status = 'canceled';
      } else if (event.end <= now) {
        status = 'completed';
      } else if (event.start <= now) {
        status = 'active';
      } else {
        status = 'upcoming';
      }

      const guestName = parseGuestName(event.summary, event.description, integration.channelName);
      const { externalUrl, externalReservationId, phoneStub } = extractFromDescription(event.description);

      const bookingData = {
        tenantId,
        guestName,
        guestPhone: phoneStub || '',
        room: integration.roomId,
        checkIn: event.start,
        checkOut: event.end,
        nights,
        nightPrice: 0,
        totalPrice: 0,
        tax: 0,
        deposit: 0,
        remaining: 0,
        status,
        source: integration.channelName,
        notes: null,                                 // notes stay clean for synced bookings
        externalId: event.uid,
        externalChannel: integration.channelName,
        externalUrl,
        externalReservationId,
        createdBy: 'channel_sync',
      };

      const existing = existingByUid.get(event.uid);
      // UID-drift rescue: when the UID lookup misses, try matching by the
      // (channel + room + check-in + check-out) fingerprint. If we find a
      // previously-synced booking for the exact same slot, this is the same
      // reservation with a drifted UID — re-link it instead of creating a new
      // zero-priced row that would shadow the user's manual price entries.
      const driftMatch = !existing
        ? driftByDates.get(fingerprint(event.start, event.end))
        : null;
      const target = existing ?? driftMatch;

      if (target) {
        // Re-fetch full row when we landed on a drift match (the index only
        // selected a subset of columns).
        const targetFull = existing
          ?? (await prisma.booking.findUnique({ where: { id: target.id } }))!;
        const wasCanceled = targetFull.status !== 'canceled' && status === 'canceled';
        // Preserve a manually-edited guest name; only overwrite if the stored name still
        // looks auto-generated (placeholder, bracketed, "Reserved", etc.)
        const safeGuestName = looksAutoGenerated(targetFull.guestName) ? guestName : targetFull.guestName;
        const safeNotes = looksAutoNotes(targetFull.notes) ? null : targetFull.notes;
        const safePhone = looksAutoPhone(targetFull.guestPhone) ? (phoneStub || '') : targetFull.guestPhone;
        await prisma.booking.update({
          where: { id: target.id },
          data: {
            guestName: safeGuestName,
            guestPhone: safePhone,
            checkIn: event.start,
            checkOut: event.end,
            nights,
            status,
            notes: safeNotes,
            externalUrl,                              // always refresh from latest description
            externalReservationId,                    // ditto — code may have been corrected on the platform
            // On a drift rescue we adopt the new UID; on a normal UID match this
            // is a no-op write of the same value. Either way, price fields
            // (nightPrice, totalPrice, tax, deposit, remaining) are deliberately
            // NOT in this payload — Prisma leaves them untouched, so anything
            // the host typed is preserved.
            externalId: event.uid,
          },
        });
        // Keep the drift index consistent for the rest of this batch so a
        // subsequent event with the same fingerprint doesn't re-link the same row.
        if (driftMatch) driftByDates.delete(fingerprint(event.start, event.end));
        wasCanceled ? canceled++ : updated++;
      } else {
        // Take the next claimed booking number — pre-allocated above so we don't
        // round-trip to Tenant once per event.
        const bookingNumber = nextBookingNumberCursor++;
        await prisma.booking.create({ data: { ...bookingData, bookingNumber } });
        imported++;
      }
    } catch (err: any) {
      errors.push(`UID ${event.uid}: ${err.message}`);
    }
  }

  // ── Orphan cancel ──
  // The channel side is the source of truth. If a booking's UID is no longer in
  // the feed (host deleted it on Airbnb / Gathern), mark our copy as canceled.
  // Scoped to future bookings only — old completed bookings naturally age out of
  // iCal feeds, so missing-from-feed != deleted for those.
  try {
    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);
    const feedUids = new Set(events.map((e) => e.uid));
    const liveOrphans = await prisma.booking.findMany({
      where: {
        tenantId,
        room: integration.roomId,
        externalChannel: integration.channelName,
        externalId: { not: null },
        status: { not: 'canceled' },
        checkOut: { gte: todayStart },
      },
      select: { id: true, externalId: true },
    });
    const toCancel = liveOrphans
      .filter((b) => b.externalId && !feedUids.has(b.externalId))
      .map((b) => b.id);
    if (toCancel.length > 0) {
      await prisma.booking.updateMany({
        where: { id: { in: toCancel } },
        data: { status: 'canceled' },
      });
      canceled += toCancel.length;
    }
  } catch (err: any) {
    // Don't fail the whole sync if the orphan sweep blows up — log and move on.
    errors.push(`orphan cancel failed: ${err.message}`);
  }

  // Soft verification — flag the integration as 'suspicious' when the feed looks off.
  // Thresholds are intentionally loose to avoid false alarms on heavy-usage properties.
  const suspiciousReasons = detectSuspiciousPatterns(events);

  let finalStatus: string;
  let finalMessage: string;
  if (errors.length > 0) {
    finalStatus = 'partial';
    finalMessage = `Imported ${imported}, updated ${updated}, canceled ${canceled}, skipped ${skipped}, errors ${errors.length}`;
  } else if (suspiciousReasons.length > 0) {
    finalStatus = 'suspicious';
    finalMessage = `Imported ${imported}, updated ${updated} — suspicious: ${suspiciousReasons.join('; ')}`;
  } else {
    finalStatus = 'success';
    finalMessage = `Imported ${imported}, updated ${updated}, canceled ${canceled}, skipped ${skipped}`;
  }

  await prisma.channelIntegration.update({
    where: { id: integration.id },
    data: {
      lastSyncedAt: new Date(),
      lastSyncStatus: finalStatus,
      lastSyncMessage: finalMessage,
      lastSyncCount: events.length,
    },
  });

  return { integrationId: integration.id, tenantId, channelName: integration.channelName, roomId: integration.roomId, imported, updated, canceled, skipped, blocksRemoved, errors, success: errors.length === 0, message: finalMessage };
}

/**
 * Heuristics to catch iCal feeds that look wrong.
 * Returns a list of human-readable reasons — empty array = looks fine.
 */
function detectSuspiciousPatterns(events: { uid: string; start: Date; end: Date; status: string }[]): string[] {
  const reasons: string[] = [];

  // 1. Excessive event count for a single listing. 300 events ~= 1 booking/day for a year —
  // well above a realistic short-term rental, likely a corrupted/combined feed.
  const confirmed = events.filter(e => e.status !== 'CANCELLED');
  if (confirmed.length > 300) {
    reasons.push(`${confirmed.length} events in feed (threshold 300)`);
  }

  // 2. Physically-impossible overlaps on the same room. Two confirmed bookings whose date
  // ranges overlap strictly — a single room can't be occupied twice at once.
  const sorted = [...confirmed].sort((a, b) => a.start.getTime() - b.start.getTime());
  let overlaps = 0;
  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i].start < sorted[i - 1].end) overlaps++;
  }
  if (overlaps >= 3) {
    reasons.push(`${overlaps} overlapping bookings on one room`);
  }

  return reasons;
}

/**
 * Sync all active integrations for a specific channel across ALL tenants.
 * Used by the cron endpoint — each platform runs on its own schedule.
 */
export async function syncAllTenantsForChannel(channel: Channel, mode?: SyncMode) {
  const integrations = await prisma.channelIntegration.findMany({
    where: {
      channelName: channel,
      isActive: true,
      tenant: { integrationsEnabled: true },
    },
  });

  const results: SyncResult[] = [];
  for (const integration of integrations) {
    try {
      results.push(await performSync(integration, integration.tenantId, mode));
    } catch (err: any) {
      results.push({
        integrationId: integration.id,
        tenantId: integration.tenantId,
        channelName: integration.channelName,
        roomId: integration.roomId,
        imported: 0, updated: 0, canceled: 0, skipped: 0, blocksRemoved: 0,
        errors: [err.message || String(err)],
        success: false,
        message: `Unhandled error: ${err.message}`,
      });
    }
  }

  return results;
}
