import { differenceInCalendarDays } from 'date-fns';
import { prisma } from './prisma';
import { fetchAndParseICal } from './icalParser';

export const VALID_CHANNELS = ['airbnb', 'gathern', 'booking.com'] as const;
export type Channel = typeof VALID_CHANNELS[number];

/**
 * Convert an iCal date-only event date to UTC midnight (00:00:00) of the SAME
 * calendar day the feed labeled — so a "June 14" check-in is stored as
 * 2026-06-14T00:00:00Z and the frontend shows June 14 everywhere.
 *
 * node-ical parses an all-day event (VALUE=DATE) as *server-local* midnight of
 * the labeled date. So we must read the LOCAL components (getFullYear/Month/Date),
 * not the UTC ones. Using getUTC* only happens to work when the server runs in
 * UTC; on any positive-offset host (Vercel's sin1 region, a Riyadh dev machine)
 * the UTC date rolls back to the previous day → the classic "one day before" bug.
 */
function toUTCMidnight(d: Date): Date {
  return new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate(), 0, 0, 0));
}

export interface SyncResult {
  integrationId: string;
  tenantId: string;
  channelName: string;
  roomId: string;
  imported: number;
  updated: number;
  canceled: number;
  skipped: number;
  blocksRemoved: number;
  errors: string[];
  success: boolean;
  message: string;
}

export function parseGuestName(summary: string, description: string | null | undefined, channel: string): string {
  const s = (summary || '').trim();

  if (!s || /closed|not available|unavailable/i.test(s)) {
    return `[${channel} block]`;
  }

  if (/^reserved$/i.test(s)) {
    const airbnbCode = description?.match(/airbnb\.com\/hosting\/reservations\/details\/([A-Z0-9]+)/i)?.[1];
    if (airbnbCode) return `Airbnb \u2022 ${airbnbCode}`;
    const gathernId = description?.match(/Booking\s*ID\s*:\s*(\d+)/i)?.[1];
    if (gathernId) return `Gathern \u2022 ${gathernId}`;
    return `[${channel} guest]`;
  }

  const byMatch = s.match(/(?:reservation|booking)\s+(?:by|from)\s+(.+)/i);
  if (byMatch) return byMatch[1].trim();

  if (/^(booking|reservation)\s*$/i.test(s)) return `[${channel} guest]`;

  return s || 'Guest';
}

function looksAutoGenerated(name: string | null | undefined): boolean {
  if (!name) return true;
  const n = name.trim();
  if (!n) return true;
  if (/^\[.+\]$/.test(n)) return true;
  if (/^reserved$/i.test(n)) return true;
  if (/^gathern\s*•\s*\d+$/i.test(n)) return true;
  if (/^airbnb\s*\u2022\s*[A-Z0-9]+$/i.test(n)) return true;
  if (n === 'Guest') return true;
  return false;
}

function looksAutoNotes(notes: string | null | undefined): boolean {
  if (!notes) return true;
  const n = notes.trim();
  if (!n) return true;
  if (/Reservation URL:/i.test(n)) return true;
  if (/Phone Number\s*\(Last\s*\d+\s*Digits?\)/i.test(n)) return true;
  if (/^https?:\/\/\S+\s*$/i.test(n)) return true;
  if (/^Booking\s*ID\s*:\s*\d+/i.test(n)) return true;
  if (/^Host\s+blocked\s*$/i.test(n)) return true;
  return false;
}

function looksAutoPhone(phone: string | null | undefined): boolean {
  if (!phone) return true;
  const p = phone.trim();
  if (!p) return true;
  if (/^[•·]+\s*\d{2,6}$/.test(p)) return true;
  return false;
}

export function extractFromDescription(description: string | null | undefined, uid?: string): {
  externalUrl: string | null;
  externalReservationId: string | null;
  phoneStub: string | null;
} {
  if (!description) return { externalUrl: null, externalReservationId: null, phoneStub: null };
  const text = description.replace(/\\n/g, '\n');

  let externalUrl: string | null = null;
  const labeled = text.match(/Reservation URL:\s*(https?:\/\/\S+)/i);
  if (labeled) {
    externalUrl = labeled[1];
  } else {
    const any = text.match(/https?:\/\/\S+/i);
    if (any) externalUrl = any[0];
  }
  if (externalUrl) externalUrl = externalUrl.replace(/[).,;]+$/, '');

  let externalReservationId: string | null = null;
  const airbnbCode = text.match(/airbnb\.com\/hosting\/reservations\/details\/([A-Z0-9]+)/i);
  if (airbnbCode) {
    externalReservationId = airbnbCode[1].toUpperCase();
  } else {
    const gathernId = text.match(/Booking\s*ID\s*:\s*(\d+)/i);
    if (gathernId) {
      externalReservationId = gathernId[1];
    } else if (uid && uid.includes('@gathern.co')) {
      const uidMatch = uid.match(/reservation-(\d+)@gathern\.co/i);
      if (uidMatch && uidMatch[1]) {
        externalReservationId = uidMatch[1].substring(0, 8);
        console.log(`[Gathern] Extracted reservation ID from UID fallback: ${externalReservationId} from ${uidMatch[1]}`);
      }
    }
  }

  let phoneStub: string | null = null;
  const last = text.match(/Phone Number\s*\(Last\s*(\d+)\s*Digits?\)\s*:\s*(\d+)/i);
  if (last) {
    phoneStub = `•••• ${last[2]}`;
  }

  return { externalUrl, externalReservationId, phoneStub };
}

export type SyncMode = 'all' | 'future';

export async function performSync(integration: any, tenantId: string, mode?: SyncMode): Promise<SyncResult> {
  let imported = 0, updated = 0, canceled = 0, skipped = 0;
  const errors: string[] = [];

  let events;
  try {
    events = await fetchAndParseICal(integration.icalUrl);
  } catch (err: any) {
    const message = `Failed to fetch iCal: ${err.message}`;
    await prisma.channelIntegration.update({
      where: { id: integration.id },
      data: { lastSyncedAt: new Date(), lastSyncStatus: 'error', lastSyncMessage: message },
    });
    return { integrationId: integration.id, tenantId, channelName: integration.channelName, roomId: integration.roomId, imported: 0, updated: 0, canceled: 0, skipped: 0, blocksRemoved: 0, errors: [message], success: false, message };
  }

  const lookbackDays: number = (() => {
    if (mode === 'all') return -1;
    if (mode === 'future') return 0;
    const stored = (integration as any).syncLookbackDays;
    if (stored === null || stored === undefined) return 0;
    return stored;
  })();
  if (lookbackDays !== -1) {
    const cutoff = new Date();
    cutoff.setHours(0, 0, 0, 0);
    if (lookbackDays > 0) cutoff.setDate(cutoff.getDate() - lookbackDays);
    const before = events.length;
    events = events.filter((e) => e.end >= cutoff);
    skipped += before - events.length;
  }

  const syncBlocks = !!integration.syncBlocks;
  const isBlockEvent = (e: { summary: string }) => {
    const s = (e.summary || '').trim();
    return !s || /closed|not available|unavailable/i.test(s);
  };
  let blocksRemoved = 0;
  if (!syncBlocks) {
    const before = events.length;
    events = events.filter((e) => !isBlockEvent(e));
    skipped += before - events.length;

    const sweep = await prisma.booking.deleteMany({
      where: {
        tenantId,
        room: integration.roomId,
        externalChannel: integration.channelName,
        guestName: { startsWith: '[', endsWith: 'block]' },
      },
    });
    blocksRemoved = sweep.count;
  }

  const candidates = events.length > 0
    ? await prisma.booking.findMany({
        where: {
          tenantId,
          room: integration.roomId,
          externalChannel: integration.channelName,
          externalId: { not: null },
        },
        select: {
          id: true, externalId: true, externalReservationId: true,
          checkIn: true, checkOut: true, status: true,
          guestName: true, notes: true, guestPhone: true,
        },
      })
    : [];
  type Candidate = (typeof candidates)[number];

  const fingerprint = (start: Date, end: Date) =>
    `${start.toISOString().slice(0, 10)}|${end.toISOString().slice(0, 10)}`;
  const better = (prior: Candidate | undefined, b: Candidate) =>
    !prior || (prior.status === 'canceled' && b.status !== 'canceled');

  const byResId = new Map<string, Candidate>();
  const byUid = new Map<string, Candidate>();
  const byDates = new Map<string, Candidate>();
  for (const b of candidates) {
    if (b.externalReservationId && better(byResId.get(b.externalReservationId), b)) byResId.set(b.externalReservationId, b);
    if (b.externalId && better(byUid.get(b.externalId), b)) byUid.set(b.externalId, b);
    const fp = fingerprint(b.checkIn, b.checkOut);
    if (better(byDates.get(fp), b)) byDates.set(fp, b);
  }

  const consume = (b: Candidate) => {
    if (b.externalReservationId) byResId.delete(b.externalReservationId);
    if (b.externalId) byUid.delete(b.externalId);
    byDates.delete(fingerprint(b.checkIn, b.checkOut));
  };

  const feedResIds = new Set<string>();
  const plan: { event: typeof events[number]; target: Candidate | null }[] = [];
  for (const event of events) {
    const resid = extractFromDescription(event.description, event.uid).externalReservationId;
    if (resid) {
      if (feedResIds.has(resid)) { skipped++; continue; }
      feedResIds.add(resid);
    }
    const normalizedStart = toUTCMidnight(event.start);
    const normalizedEnd = toUTCMidnight(event.end);
    const nights = differenceInCalendarDays(normalizedEnd, normalizedStart);
    if (nights <= 0) { skipped++; continue; }
    
    const dateCandidate = byDates.get(fingerprint(normalizedStart, normalizedEnd));
    const dateMatch =
      dateCandidate &&
      !(resid && dateCandidate.externalReservationId && dateCandidate.externalReservationId !== resid)
        ? dateCandidate
        : undefined;
    const target =
      (resid ? byResId.get(resid) : undefined)
      ?? byUid.get(event.uid)
      ?? dateMatch
      ?? null;
    if (target) consume(target);
    plan.push({ event: { ...event, start: normalizedStart, end: normalizedEnd }, target });
  }

  const newCount = plan.filter((p) => !p.target).length;
  let nextBookingNumberCursor = 0;
  if (newCount > 0) {
    const claimed = await prisma.tenant.update({
      where: { id: tenantId },
      data: { nextBookingNumber: { increment: newCount } },
      select: { nextBookingNumber: true },
    });
    nextBookingNumberCursor = claimed.nextBookingNumber - newCount;
  }

  for (const { event, target } of plan) {
    try {
      const nights = differenceInCalendarDays(event.end, event.start);

      const now = new Date();
      let status: string;
      if (event.status === 'CANCELLED') {
        status = 'canceled';
      } else if (event.end <= now) {
        status = 'completed';
      } else if (event.start <= now) {
        status = 'active';
      } else {
        status = 'upcoming';
      }

      const guestName = parseGuestName(event.summary, event.description, integration.channelName);
      const { externalUrl, externalReservationId, phoneStub } = extractFromDescription(event.description, event.uid);

      if (target) {
        const wasCanceled = target.status !== 'canceled' && status === 'canceled';
        const safeGuestName = looksAutoGenerated(target.guestName) ? guestName : target.guestName;
        const safeNotes = looksAutoNotes(target.notes) ? null : target.notes;
        const safePhone = looksAutoPhone(target.guestPhone) ? (phoneStub || '') : target.guestPhone;
        await prisma.booking.update({
          where: { id: target.id },
          data: {
            guestName: safeGuestName,
            guestPhone: safePhone,
            checkIn: event.start,
            checkOut: event.end,
            nights,
            status,
            notes: safeNotes,
            externalUrl,
            externalReservationId,
            externalId: event.uid,
          },
        });
        wasCanceled ? canceled++ : updated++;
      } else {
        // Synced bookings carry no pricing data from the channel feeds, so we
        // create them with zeros and let the host enter prices manually. Their
        // edits are preserved on every subsequent resync (the UPDATE block
        // above never writes price fields, and the drift-rescue path adopts a
        // new UID onto the existing row without touching money fields).
        const bookingNumber = nextBookingNumberCursor++;
        await prisma.booking.create({
          data: {
            tenantId,
            guestName,
            guestPhone: phoneStub || '',
            room: integration.roomId,
            checkIn: event.start,
            checkOut: event.end,
            nights,
            nightPrice: 0,
            totalPrice: 0,
            tax: 0,
            deposit: 0,
            remaining: 0,
            status,
            source: integration.channelName,
            notes: null,
            externalId: event.uid,
            externalChannel: integration.channelName,
            externalUrl,
            externalReservationId,
            createdBy: 'channel_sync',
            bookingNumber,
          },
        });
        imported++;
      }
    } catch (err: any) {
      errors.push(`UID ${event.uid}: ${err.message}`);
    }
  }

  // ── Orphan cancel with special handling for Gathern ──
  try {
    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);
    const feedUids = new Set(events.map((e) => e.uid));
    const liveOrphans = await prisma.booking.findMany({
      where: {
        tenantId,
        room: integration.roomId,
        externalChannel: integration.channelName,
        externalId: { not: null },
        status: { not: 'canceled' },
        checkOut: { gte: todayStart },
      },
      select: { id: true, externalId: true, externalReservationId: true, checkIn: true, status: true },
    });
    
    const toCancel = liveOrphans
      .filter((b) => {
        const uidInFeed = !!b.externalId && feedUids.has(b.externalId);
        const residInFeed = !!b.externalReservationId && feedResIds.has(b.externalReservationId);
        
        // SPECIAL HANDLING FOR GATHERN
        if (integration.channelName === 'gathern') {
          const isFuture = b.checkIn > new Date();
          if (isFuture) {
            // NEVER auto-cancel future Gathern bookings - UID churn makes this unreliable
            console.log(`[Gathern] Skipping auto-cancel for future booking: ID=${b.id}, ResID=${b.externalReservationId}, CheckIn=${b.checkIn}`);
            return false;
          }
          
          // For past Gathern bookings, be more lenient - only cancel if BOTH IDs are missing
          const isCompleted = b.checkIn < todayStart;
          if (!uidInFeed && !residInFeed && !isCompleted) {
            console.log(`[Gathern] Would cancel future booking but prevented: ${b.id}`);
            return false;
          }
        }
        
        return !uidInFeed && !residInFeed;
      })
      .map((b) => b.id);
      
    if (toCancel.length > 0) {
      console.log(`[${integration.channelName}] Canceling ${toCancel.length} orphan bookings: ${toCancel.join(', ')}`);
      await prisma.booking.updateMany({
        where: { id: { in: toCancel } },
        data: { status: 'canceled' },
      });
      canceled += toCancel.length;
    } else {
      if (integration.channelName === 'gathern') {
        console.log(`[Gathern] No orphan cancellations performed`);
      }
    }
  } catch (err: any) {
    errors.push(`orphan cancel failed: ${err.message}`);
    console.error(`[Gathern] Orphan cancel error:`, err);
  }

  const suspiciousReasons = detectSuspiciousPatterns(events);

  let finalStatus: string;
  let finalMessage: string;
  if (errors.length > 0) {
    finalStatus = 'partial';
    finalMessage = `Imported ${imported}, updated ${updated}, canceled ${canceled}, skipped ${skipped}, errors ${errors.length}`;
  } else if (suspiciousReasons.length > 0) {
    finalStatus = 'suspicious';
    finalMessage = `Imported ${imported}, updated ${updated} — suspicious: ${suspiciousReasons.join('; ')}`;
  } else {
    finalStatus = 'success';
    finalMessage = `Imported ${imported}, updated ${updated}, canceled ${canceled}, skipped ${skipped}`;
  }

  await prisma.channelIntegration.update({
    where: { id: integration.id },
    data: {
      lastSyncedAt: new Date(),
      lastSyncStatus: finalStatus,
      lastSyncMessage: finalMessage,
      lastSyncCount: events.length,
    },
  });

  return { integrationId: integration.id, tenantId, channelName: integration.channelName, roomId: integration.roomId, imported, updated, canceled, skipped, blocksRemoved, errors, success: errors.length === 0, message: finalMessage };
}

function detectSuspiciousPatterns(events: { uid: string; start: Date; end: Date; status: string }[]): string[] {
  const reasons: string[] = [];

  const confirmed = events.filter(e => e.status !== 'CANCELLED');
  if (confirmed.length > 300) {
    reasons.push(`${confirmed.length} events in feed (threshold 300)`);
  }

  const sorted = [...confirmed].sort((a, b) => a.start.getTime() - b.start.getTime());
  let overlaps = 0;
  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i].start < sorted[i - 1].end) overlaps++;
  }
  if (overlaps >= 3) {
    reasons.push(`${overlaps} overlapping bookings on one room`);
  }

  return reasons;
}

export async function syncAllTenantsForChannel(channel: Channel, mode?: SyncMode) {
  const integrations = await prisma.channelIntegration.findMany({
    where: {
      channelName: channel,
      isActive: true,
      tenant: { integrationsEnabled: true },
    },
  });

  const results: SyncResult[] = [];
  for (const integration of integrations) {
    try {
      results.push(await performSync(integration, integration.tenantId, mode));
    } catch (err: any) {
      results.push({
        integrationId: integration.id,
        tenantId: integration.tenantId,
        channelName: integration.channelName,
        roomId: integration.roomId,
        imported: 0, updated: 0, canceled: 0, skipped: 0, blocksRemoved: 0,
        errors: [err.message || String(err)],
        success: false,
        message: `Unhandled error: ${err.message}`,
      });
    }
  }

  return results;
}